# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71211b3cfecc6e2ec21cd18c96c178cdf048c917fc4d1593eb17e457bd720e59e210e80020426e1807f3e65f20806b0bd106b3dabb495b418973080262f77e4a

test:
  secret_key_base: f16b4b1ad87ed2f2d441e124af333ef22e0cae3e5d842f4b8651316ffa2b92f0b704880ec821530275f646353ca92fa5acc9ef79c7353ea57713ec4ff56566ef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
